name: Esdiel CI

on:
  push:
    paths:
      - 'scripts/**'
      - 'lambda_function.py'
    branches: [main]
  pull_request:
    paths:
      - 'scripts/**'
      - 'lambda_function.py'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Format and lint Python code
        run: |
          make format && make lint
